config/routes.rb
Infomanager::Application.routes.draw do

  match '/users/dashboard' => "dashboard#dashboard", :as => :dashboard
  resources :users
  resources :user_sessions
  match '/login' => "user_sessions#new", :as => :login
  match '/logout' => "user_sessions#destroy", :as => :logout
  
  
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/models/split.rb
class Split < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field = :email
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.create(params[:user_session])
    if @user_session.save
      flash[:notice] = "Successfully Logged In."
      redirect_to dashboard_url
    else
      flash[:error] = "The credentials you provided were invalid"
      redirect_to login_url
    end
  end
  
  def destroy
    @user_session = UserSession.find
    @user_session.destroy unless @user_session.blank?
    flash[:notice] = "Successfully Logged Out"
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def login
    render :text => "Login Action Called"
  end
  
  def logout
    render :text => "Logout Action Called"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Infomanager</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dashboard.html.haml
!!! html
%html
  %head
    %meta( charset='utf-8' )
    %title
      Your Account dashboard
    = stylesheet_link_tag("dashboard")
    /[if IE]
      = stylesheet_link_tag("common/ie")
    /[if lte IE 6]
      = stylesheet_link_tag("common/ie6")
    /[if gte IE 7]
      = stylesheet_link_tag("common/ie7")
    %script{:src => "http://use.typekit.com/xxt0wsb.js" }
    %script
      try{Typekit.load();}catch(e){}
    = javascript_include_tag "jquery.min","highcharts/highcharts"
    
    = yield :charts_js
  %body
    #focus
      #header
        #logo
          Your Dashboard
        %ul.horizontal
          %li
            = link_to "Profile", "#"
          %li
            = link_to "Do Something", "#"
          %li
            = link_to "Logout", logout_url
      #content.clear
        = yield
      #footer
        Footer Content
    
    
                

app/views/layouts/users.html.haml
- form_for @user do |f|
  = f.label :email, "Email Address"
  = f.text_field :email
  = f.label :password, "Password"
  = f.password_field :password
  = f.label :password_confirmation, "Password Confirmation"
  = f.password_field :password_confirmation
  = f.submit "Submit"
  

app/views/user_sessions/new.html.haml
- form_for @user_session do |f|
  = f.label :email, "Email Address"
  = f.text_field :email
  = f.label :password, "Password"
  = f.password_field :password
  = f.submit "Login"
  
  